### ISSUE TITLE
Remove unused routes

### ISSUE THREAD

**Issue by dummied** [firestorm451/PlasticRecyc#11]
And their associated controller actions and views.

BoxesController#index, for instance

**Comment by dummied** [comment]
Boxes edit/update as well I think.

If not, boxes#update will fail (@box is nil)

**Comment by dummied** [comment]
Customer edit/update

**Comment by dummied** [comment]
Location edit/update

**Comment by dummied** [comment]
Machine edit/update

**Comment by dummied** [comment]
Material edit/update

**Comment by dummied** [comment]
Users show?

**Comment by firestorm451** [comment]
Thanks, locking down those routes!
