### ISSUE TITLE
Multiple id's on a page

### ISSUE THREAD

**Issue by dummied** [firestorm451/PlasticRecyc#18]
https://github.com/firestorm451/ButlerMacdonald/blob/master/app/views/jobs/_job.html.erb#L2-L14

Since this partial is rendered X times, you'll end up with multiple ids on the page. Either remove them or use classes instead.

**Comment by dummied** [comment]
https://github.com/firestorm451/ButlerMacdonald/blob/master/app/views/machines/_job.html.erb#L2-L5

**Comment by firestorm451** [comment]
Yep, going to be better to call them as classes rather than ids, thanks.
