### ISSUE TITLE
Remove .DS_Store

### ISSUE THREAD

**Issue by dummied** [firestorm451/PlasticRecyc#7]
Here's one: https://github.com/firestorm451/ButlerMacdonald/blob/master/app/.DS_Store

Remove it (and any others) and I'd suggest adding it to your `.gitignore`

**Comment by dummied** [comment]
https://github.com/firestorm451/ButlerMacdonald/blob/master/app/assets/.DS_Store

**Comment by firestorm451** [comment]
Added and thanks
